font_family JetBrainsMono Nerd Font Mono
font_size 12

disable_ligatures no
enable_audio_bell no

shell zsh
shell_integration disabled

cursor_shape block
cursor_blink_interval 0
cursor_trail 1
cursor_trail_decay 0.1 0.4

url_style curly

remember_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 20

background_opacity 0.65
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

confirm_os_window_close 0
sync_to_monitor no

allow_remote_control yes

tab_bar_style powerline
tab_bar_min_tabs 1

map ctrl+alt+s launch --type=overlay /bin/bash -c '$HOME/.config/kitty/scripts/sessions.sh'
map ctrl+alt+l launch kitten quick-access-terminal /bin/bash -c '$HOME/.config/kitty/scripts/launch.sh'
map ctrl+alt+x close_tab
